# This is Simple nginx pod taml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: Dev
    type: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
