# This is Simple nginx pod yaml
apiVersion: v1
kind: Pod
metadata:
  name: ngnix-app-pod
  labels:
    env: Dev
    type: frontend
spec:
  containers:
  - name: ngnix-app-container
    image: ngnix:latest
    labels:
      env: Dev
      type: frontend
    ports:
    - containerPort: 80
