# This is simple nginx pod yaml file
apiVersion: v1
kind: Pod
metadata:
  name: nginx-app-pod
  labels:
    env: Dev
    type: frontend
spec:
  containers: 
  - name: ginx-app-container
    image: nginx:latest
    ports:
    - containerPort: 80
