# This is simple ngnix pod yaml file
apiVersion: v1
kind: Pod
metadata:
  name: ngnix-app1-pod
  labels:
    env: Dev
    type: frontend
spec:
  containers:
  - name: ngnix-app1-container
    image: ngnix:latest
    ports:
    containerPort: 80