# This is the ReplicaSet yaml file

# GROUP:      apps
# KIND:       ReplicaSet
# VERSION:    v1


apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels: 
    env: Dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: Dev
      type: frontend
  template:
    metadata:
      name: nginx-pod
      labels:
        env: Dev
        type: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80