# This is the Deployment yaml file
# --> how to check the version and group
# [root@kubernetes-master ~]# kubectl explain deployments 
# GROUP:      apps
# KIND:       Deployment
# VERSION:    v1



apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels: 
    env: Dev
    type: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      env: Dev
      type: frontend
  template:
    metadata:
      name: nginx-pod
      labels:
        env: Dev
        type: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80



