kind: Pod
apiVersion: v1
metadata:
  name: EVN
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: techbasehub
      value: "DevOps Engg"
    - name: location
      value: Gutur
    - name: organization
      value: "techbasehub.com" 