# This file is Service yaml file

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    env: Dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    env: Dev
