# This file is DaemonSet yaml file

apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: nginx-ds
  labels:
    env: app
spec:
  template:
    metadata:
      name: ngnix 
      labels:
        env: app
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      env: app
