apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
spec:
  containers:
    - name: demo-container
      image: busybox
      command: [ "sh", "-c", "echo USER=$USERNAME && echo PASS=$PASSWORD && sleep 3600" ]
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret-user-passwd
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret-user-passwd
              key: password
