kind: Service
apiVersion: v1
metadata:
  name: nginx-non-prod
spec:
  type: NodePort
  selector: # labels are used as selectors
    project: services
    component: backend
    environment: dev
    version: "1.0.0"
    demo: np
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007
---
kind: Pod
apiVersion: v1
metadata:
  name: non-prod-services
  labels:
    project: services
    component: backend
    environment: dev
    version: "1.0.0"
    demo: np
spec:
  containers:
  - name: nginx
    image: nginx
    