apiVersion: v1
kind: Pod

metadata:
  name: my-pod

spec:
  containers:
  - name: nginx
    image: nginx

    env:
    - name: APP_NAME
      valueFrom:
        configMapKeyRef:
          name: webapp-config
          key: APP_NAME

    - name: ENVIRONMENT
      valueFrom:
        configMapKeyRef:
          name: webapp-config
          key: ENVIRONMENT