# This is Secret yaml file
# To check the verison for Secret 
# [root@kubernetes-master kubernetes]# kubectl explain Secret
# KIND:       Secret
# VERSION:    v1
# How to encript and decript using base 64
# [root@kubernetes-master kubernetes]# echo "admin" | base64
# YWRtaW4K
# [root@kubernetes-master kubernetes]# echo "YWRtaW4K" | base64 -d
# admin
# [root@kubernetes-master kubernetes]# echo "1234546" | base64
# MTIzNDU0Ngo=



apiVersion: v1
kind: Secret
metadata: 
  name: my-secret
type: Opaque
date:
  username: YWRtaW4K
  password: MTIzNDU0Ngo=