# This is Secret yaml file
# To check the verison for Secret 
# [root@kubernetes-master kubernetes]# kubectl explain Secret
# KIND:       Secret
# VERSION:    v1

apiVersion: v1
kind: Secret
metadata: 
  name: my-secret
type: Opaque
stringData:
  username: YWRtaW4K
  password: MTIzNDU0Ngo=